# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FORTHWINDOW.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(888, 551)
        MainWindow.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0.497, y1:0.0397727, x2:0.497291, y2:0.938, stop:0.115578 rgba(51, 23, 100, 255), stop:0.447236 rgba(40, 47, 117, 255), stop:0.683417 rgba(30, 76, 136, 255), stop:0.869347 rgba(26, 99, 154, 255))")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(463, 10, 140, 41))
        self.label_3.setStyleSheet("background-color: transparent;\n"
"color:white;")
        self.label_3.setObjectName("label_3")
        self.positions = QtWidgets.QTableWidget(self.centralwidget)
        self.positions.setGeometry(QtCore.QRect(460, 60, 400, 470))
        self.positions.setStyleSheet("QTableWidget{\n"
"background-color: rgb(245, 245, 245);\n"
"}")
        self.positions.setAutoScrollMargin(11)
        self.positions.setAlternatingRowColors(False)
        self.positions.setIconSize(QtCore.QSize(0, 0))
        self.positions.setObjectName("positions")
        self.positions.setColumnCount(5)
        self.positions.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.positions.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.positions.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.positions.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.positions.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.positions.setHorizontalHeaderItem(4, item)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(440, 40, 10, 470))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.courbefitness = QtWidgets.QWidget(self.centralwidget)
        self.courbefitness.setGeometry(QtCore.QRect(20, 188, 400, 337))
        self.courbefitness.setStyleSheet("background-color:rgb(245, 245, 245)")
        self.courbefitness.setObjectName("courbefitness")
        self.content_plot = QtWidgets.QWidget(self.courbefitness)
        self.content_plot.setGeometry(QtCore.QRect(0, 0, 400, 340))
        self.content_plot.setObjectName("content_plot")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, -50, 301, 301))
        self.label_4.setStyleSheet("background-color: transparent;\n"
"border-image: url(:/newPrefix/icon5g.png)")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(22, 150, 141, 41))
        self.label_2.setStyleSheet("background-color: transparent;\n"
"color:white;")
        self.label_2.setObjectName("label_2")
        self.label_4.raise_()
        self.label_3.raise_()
        self.positions.raise_()
        self.line_2.raise_()
        self.courbefitness.raise_()
        self.label_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "POSITIONS "))
        item = self.positions.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "N° gNodeB"))
        item = self.positions.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "X"))
        item = self.positions.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Y"))
        item = self.positions.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Etat"))
        item = self.positions.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Energie"))
        self.label_2.setText(_translate("MainWindow", "COURBE DE FITNESS"))
import ressources_rc
